apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
  - name: python-app-container
    image: ayushbhatnagar/python-docker
    ports:
    - name: flask-port
      containerPort: 5000
