apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  ports:
  - port: 31001
    nodePort: 31003
    targetPort: flask-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort 
