apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    app: helloflask
spec:
  containers:
  - name: flask-app-container
    image: ayushbhatnagar/python-docker
    ports:
    - name: flask-port
      containerPort: 5000
